### ISSUE TITLE
Rearrange layout to give more prominence to the generated link

### ISSUE THREAD

**Issue by v9y** [umanghome/twitter-search-covid19#10]
It might be better to rearrange certain sections to improve visibility of important items. If you can make it a 3-column layout on desktop that'd be great. In that scenario, Tips, Resources, and other footer items can go to the left column. But if that's not easy, you may want to move the generated link on the top of the right column and make it a bit more prominent. Here's a mockup of what I mean: 
![image](https://user-images.githubusercontent.com/1576911/115571471-056c3c80-a28d-11eb-8fb5-91e602fbfca4.png)

**Comment by umanghome** [comment]
Thanks for this! I ended up putting the generated link within a modal because even I got confused at times about where the generated links are on the page.
