### ISSUE TITLE
Make generated links more prominent

### ISSUE THREAD

**Issue by umanghome** [umanghome/twitter-search-covid19#11]
Added `window.alert` earlier today but this could be better.

**Comment by harshit98** [comment]
Hey @umanghome , are there any open issues which needs to be looked after? I can help you.

**Comment by saurabhdaware** [comment]
Hi @umanghome how about we add a direct link to the Twitter on top only without having the popup?

**Comment by umanghome** [comment]
Direct links were there before but it's not very obvious to the user (including me) which part of the screen has the links once they are generated. Introduced the modal just yesterday which fixes this.

**Comment by saurabhdaware** [comment]
Oh no I meant instead of "generate links" button, we just add "visit twitter" button that takes them to twitter without generating it separately and we can make the current popup appear only when there are two or more cities to search. 

This will reduce the number of clicks required to go to search.

**Comment by umanghome** [comment]
Makes sense. I don't want to change the text of Generate Links button because there are quite a few tutorials floating around the web and I don't want those to break significantly.

We can add another button (or a link?) that says "Visit Twitter" or something when there's only one link available. There would be two buttons present when there's only one city name available.

Also, a lot of people (including me) just end up copying the generated link to share with other people over WhatsApp/Twitter. This would become difficult if the only button present on the page redirected the user to the app (on mobile phones with the app installed). So we'll give them an option to go directly to Twitter, or generate links and do whatever they want with the links.

Another reason why I prefer the modal approach is that I get to tell the user to click on the Latest tab. If the link gets opened in the app, it gets sorted by Top instead of Latest (this is a bug in the Twitter apps). With the older layout where there was no modal, quite a few people said I should sort the Tweets by Latest and not by Top.

![image](https://user-images.githubusercontent.com/5698706/115958355-c0face00-a524-11eb-8b33-456b95959ece.png)
