### ISSUE TITLE
README IMPORTANT

### ISSUE THREAD

**Issue by ghost** [umanghome/twitter-search-covid19#28]
Why are you **not merging the branches?** people are contributing and you are not merging?
Please do merge the branches, their is not conflict in those branches.

**Comment by xyzshantaram** [comment]
I've been considering forking this repo and hosting it myself, since the maintainers seem to not want outside help even though everyone is pitching in to help.

**Comment by umanghome** [comment]
Feel free to fork it, but I have a million other things to do during the day as well. I've been [merging smaller PRs](https://github.com/umanghome/twitter-search-covid19/pulls?q=is%3Apr+is%3Amerged+-author%3Aumanghome) that I can review while taking a dump.

**Comment by TanayKarve** [comment]
Hey @shantaram3013 , @backdropfilter I have created a different version inspired from this repo. Contributions are welcome and I will be actively developing it. I have made some changes to UI, made it simpler and better.

[repo](https://github.com/TanayKarve/covid19-resources-finder)
